MAID-2527 refactor/snippet: changes MData entries forEach to listEntries
maidsafe/safe_examples pull request #380
Opened 2018-05-07 20:39 UTC by hunterlester

2018-05-07 20:39 UTC, maidsafe-highfive commented
r? @krishnaIndia

(maidsafe_highfive has picked a reviewer for you, use r? to override)

2018-05-08 08:54 UTC, bochaco commented on safe_web_api_playground/static/js/code-snippets/safeMutableDataEntries.js
> +	console.log(entriesArray);
Perhaps we can still do a forEach on the array and log the values as before so people understand the object we are returning for each entry?

2018-05-10 11:01 UTC, bochaco requested changes
@hunterlester , there are some issues with the formating in some of the lines, can you please fix that and we can then merge this?

2018-05-10 14:09 UTC, hunterlester commented
formatting fixed

2018-05-10 14:38 UTC, bochaco approved these changes

2018-05-10 14:38 UTC, bochaco commented
Let's merge this only once we have a version of the browser which actually supports the changed API.

2018-09-18 17:02 UTC, hunterlester commented
PR is obsolete because it's for deprecated API. Closing.

2018-09-18 17:02 UTC, closed without merging