fix: add String "keys" to Safe Web App and Safe Electron examples for…
maidsafe/safe_examples pull request #410
Opened 2019-01-03 12:59 UTC by manavbp

… inserting

new mutations

resolves #409

2019-01-03 12:59 UTC, maidsafe-highfive commented
Thanks for the pull request, and welcome! The MaidSafe team is excited to review your changes, and you should hear from @krishnaIndia (or someone else) soon.

If any changes to this PR are deemed necessary, please add them as extra commits. This ensures that the reviewer can see what has changed since they last reviewed the code. The way GitHub handles out-of-date commits, this should also make it reasonably obvious what issues have or haven't been addressed. Large or tricky changes may require several passes of review and changes.

Please see [CONTRIBUTOR.md](../blob/master/CONTRIBUTOR) for more information.

2019-01-29 19:05 UTC, bochaco requested changes
We have been investigating this with @hunterlester , and the issue is not with the tutorial (it was in fact working for safe-node-app v0.9.1 or earlier), but with safe-node-app v0.10.x. The safe_app lib supports a key to be a number or a string, so the safe-node-app shall also support both data types for an entry's key.

2019-02-01 18:03 UTC, bochaco approved these changes

2019-02-01 18:09 UTC, hunterlester approved these changes

2019-02-01 18:33 UTC, merged